apiVersion: apps/v1
kind: Deployment
metadata:
  name: eesdevops-wordpress-deployment
  labels:
    app: eesdevops-wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eesdevops-wordpress
  template:
    metadata:
      labels:
        app: eesdevops-wordpress
    spec:
      containers:
        - name: eesdevops-wordpress
          image: wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "eesdevops-mysqlserver.mysql.database.azure.com"
            - name: WORDPRESS_DB_USER
              value: "mysqladminun"
            - name: WORDPRESS_DB_PASSWORD
              value: "H@Sh1CoR3!"
            - name: WORDPRESS_DB_NAME
              value: "eestf-wordpressdb"
