pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - terraform-job/

variables:
- group: terraform-secrets

stages:

- template: terraform-stages-template.yml
  parameters:
    environment: test
    environmentDisplayName: Test
    # Pass variables as environment variables.
    # Terraform recognizes TF_VAR prefixed environment variables.
    TerraformEnvVariables:
      TF_VAR_department: engineering
      TF_VAR_subscription_id: ${subscription_id}
      TF_VAR_client_id: ${client_id}
      TF_VAR_client_secret: ${client_secret}
      TF_VAR_tenant_id: ${tenant_id}
